export { default as HomePage } from "./HomePage"
export { default as SearchPage } from "./SearchPage"
export { default as HeroesPage } from "./HeroesPage"
export { default as TeamPage } from "./TeamPage"
export { default as HeroPage } from "./HeroPage"